import { NextRequest } from "next/server";
import { withAuth } from "@/lib/middleware";
import { successResponse, errorResponse } from "@/lib/api-response";
import { JWTPayload } from "@/lib/auth";
import { deliveryCityScope } from "@/lib/delivery-guard";
import { createPartyUser, deliveryErrorResponse } from "@/lib/delivery-service";

/**
 * Create a delivery party login for the caller's own city.
 *
 * The password is generated by the Delivery service and returned exactly once —
 * it is not stored in plaintext and cannot be recovered later. The client must
 * show it immediately.
 */
export const POST = withAuth(async (request: NextRequest, _context, user: JWTPayload) => {
  const scope = deliveryCityScope(user);
  if (!scope.ok) return errorResponse("FORBIDDEN", scope.message, 403);

  let body: { fullName?: unknown; username?: unknown; phone?: unknown };
  try {
    body = await request.json();
  } catch {
    return errorResponse("VALIDATION_ERROR", "A JSON body is required");
  }

  const fullName = typeof body.fullName === "string" ? body.fullName.trim() : "";
  const username = typeof body.username === "string" ? body.username.trim().toLowerCase() : "";
  const phone = typeof body.phone === "string" && body.phone.trim() ? body.phone.trim() : undefined;

  if (!fullName) return errorResponse("VALIDATION_ERROR", "A full name is required");
  if (!username) return errorResponse("VALIDATION_ERROR", "A username is required");
  if (username.length < 3 || username.length > 100) {
    return errorResponse("VALIDATION_ERROR", "Username must be 3-100 characters");
  }
  if (!/^[a-z0-9._-]+$/.test(username)) {
    return errorResponse("VALIDATION_ERROR", "Username may use letters, numbers, dot, dash and underscore only");
  }

  try {
    // No cityId is sent: the Delivery service derives it from the service call.
    const created = await createPartyUser(scope.cityId, { fullName, username, phone });
    return successResponse(created, "Party user created. Copy the password now — it cannot be shown again.", 201);
  } catch (error) {
    const { code, message, status } = deliveryErrorResponse(error);
    return errorResponse(code, message, status);
  }
});
